/**
 * Distance. Reference tables (src/data/*.json) are facts about the Netherlands,
 * generated by scripts/build-geo.ts from open Dutch government sources and
 * committed with their retrieval date. No provider record knows about them, and
 * a distance is never stored — it is derived at render (spec §6).
 */
import cityData from "../data/city-centroids.json";

export interface Centroid {
  lat: number;
  lon: number;
}

const CITIES = cityData.cities as Record<string, { lat: number; lon: number; provincie?: string }>;

const R_EARTH_KM = 6371;
const rad = (deg: number) => (deg * Math.PI) / 180;

export function distanceKm(a: Centroid, b: Centroid): number {
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R_EARTH_KM * Math.asin(Math.sqrt(h)) * 10) / 10;
}

/**
 * A coordinate we can actually compute with. The reference tables are generated
 * and committed, so a corrupt entry (a null, a string, a NaN from a truncated
 * write) is a real possibility — and it does not stay contained: it flows into
 * distanceKm(), which returns NaN, and NaN passes `km == null ? unplaceable : near`
 * and, under "heel NL" (`radiusKm == null`), lands the row in `near` carrying
 * `distanceKm: NaN`. The cell then prints "NaN km" beside a named business.
 *
 * An unusable coordinate is the same thing as no coordinate: the row is
 * unplaceable, and it renders under "Locatie niet vermeld" — a visible gap, which
 * is what it is.
 */
function usable(c: { lat: number; lon: number } | undefined): c is Centroid {
  return c != null && Number.isFinite(c.lat) && Number.isFinite(c.lon);
}

export function cityCentroid(city: string): Centroid | null {
  const c = CITIES[city];
  return usable(c) ? { lat: c.lat, lon: c.lon } : null;
}

/**
 * WHY a row has no distance — because `null` conflated two different statements,
 * and one of them was about a named business.
 *
 * `nearestKm` returns null both when the record holds NO city at all and when it
 * holds a city we cannot geocode. The listing printed one heading over both:
 * "Locatie niet vermeld — wij kunnen deze niet plaatsen". Over the second kind
 * that is a FALSE STATEMENT ABOUT A NAMED BUSINESS — the provider did state a
 * location, our tables simply do not hold it — printed directly above a row whose
 * own city cell shows the very location the heading says was not given.
 *
 * The two are not the same kind of thing at all:
 *
 *   no_city     — the record holds no city. A fact about the RECORD, and what the
 *                 row's own city cell already says ("locatie niet vermeld").
 *   no_centroid — the record holds a city; OUR centroid table does not. A GAP IN
 *                 OUR DATA, and it must be worded as ours. The cities are carried
 *                 along so a heading (or a bug report) can name what we missed.
 *
 * Today no provider is either — which is exactly why this was safe to get wrong,
 * and exactly why it is pinned by a test that manufactures both.
 */
export type Placement =
  | { kind: "placed"; km: number }
  | { kind: "no_city" }
  | { kind: "no_centroid"; cities: string[] };

/**
 * Place a row's cities against an origin, and SAY WHICH KIND OF NOTHING it is when
 * it cannot be placed. The distance is to the nearest placeable city — never 0
 * ("right here") and never Infinity ("far away"); both would be lies.
 */
export function placeCities(cities: string[], origin: Centroid): Placement {
  if (!cities.length) return { kind: "no_city" };
  const found = cities.map(cityCentroid).filter((c): c is Centroid => c != null);
  // A city we hold and cannot place is our miss, not their omission.
  if (!found.length) return { kind: "no_centroid", cities };
  return { kind: "placed", km: Math.min(...found.map((c) => distanceKm(origin, c))) };
}

/**
 * Distance to the nearest placeable city. null when none can be placed — NOT 0
 * (which would mean "right here") and NOT Infinity (which would sort it as far
 * away). Both would be lies; null makes it a visible gap.
 *
 * Callers that must SAY something to a reader about the null want placeCities()
 * above: the two reasons for it are not interchangeable.
 */
export function nearestKm(cities: string[], origin: Centroid): number | null {
  const p = placeCities(cities, origin);
  return p.kind === "placed" ? p.km : null;
}

/** "3512 KT" | "3512kt" | "3512" → "3512". Dutch PC4 runs 1000–9999. */
export function parsePostcode(input: string): string | null {
  const m = /^\s*(\d{4})\s*[a-z]{0,2}\s*$/i.exec(input);
  if (!m) return null;
  const pc4 = m[1];
  return Number(pc4) >= 1000 ? pc4 : null;
}

/**
 * Lazy — the 4,070-row table (32 KB gzipped) is only fetched when a visitor
 * actually uses the location filter. Everyone else pays nothing.
 */
export async function pc4Centroid(pc4: string): Promise<Centroid | null> {
  const mod = await import("../data/pc4-centroids.json");
  const table = (mod.default as unknown as { pc4: Record<string, [number, number]> }).pc4;
  const hit = table[pc4];
  if (!hit) return null;
  const c = { lat: hit[0], lon: hit[1] };
  // Same rule as cityCentroid: an unusable coordinate is no coordinate. Here it
  // is the visitor's own origin, so every distance on the page would be NaN —
  // "postcode onbekend" is the honest answer, not a table full of "NaN km".
  return usable(c) ? c : null;
}
