/**
 * Distance. Reference tables (src/data/*.json) are facts about the Netherlands,
 * generated by scripts/build-geo.ts from open Dutch government sources and
 * committed with their retrieval date. No provider record knows about them, and
 * a distance is never stored — it is derived at render (spec §6).
 */
import cityData from "../data/city-centroids.json";

export interface Centroid {
  lat: number;
  lon: number;
}

const CITIES = cityData.cities as Record<string, { lat: number; lon: number; provincie?: string }>;

const R_EARTH_KM = 6371;
const rad = (deg: number) => (deg * Math.PI) / 180;

export function distanceKm(a: Centroid, b: Centroid): number {
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R_EARTH_KM * Math.asin(Math.sqrt(h)) * 10) / 10;
}

/**
 * A coordinate we can actually compute with. The reference tables are generated
 * and committed, so a corrupt entry (a null, a string, a NaN from a truncated
 * write) is a real possibility — and it does not stay contained: it flows into
 * distanceKm(), which returns NaN, and NaN passes `km == null ? unplaceable : near`
 * and, under "heel NL" (`radiusKm == null`), lands the row in `near` carrying
 * `distanceKm: NaN`. The cell then prints "NaN km" beside a named business.
 *
 * An unusable coordinate is the same thing as no coordinate: the row is
 * unplaceable, and it renders under "Locatie niet vermeld" — a visible gap, which
 * is what it is.
 */
function usable(c: { lat: number; lon: number } | undefined): c is Centroid {
  return c != null && Number.isFinite(c.lat) && Number.isFinite(c.lon);
}

export function cityCentroid(city: string): Centroid | null {
  const c = CITIES[city];
  return usable(c) ? { lat: c.lat, lon: c.lon } : null;
}

/**
 * Distance to the nearest placeable city. null when none can be placed — NOT 0
 * (which would mean "right here") and NOT Infinity (which would sort it as far
 * away). Both would be lies; null makes it a visible gap.
 */
export function nearestKm(cities: string[], origin: Centroid): number | null {
  const found = cities.map(cityCentroid).filter((c): c is Centroid => c != null);
  if (!found.length) return null;
  return Math.min(...found.map((c) => distanceKm(origin, c)));
}

/** "3512 KT" | "3512kt" | "3512" → "3512". Dutch PC4 runs 1000–9999. */
export function parsePostcode(input: string): string | null {
  const m = /^\s*(\d{4})\s*[a-z]{0,2}\s*$/i.exec(input);
  if (!m) return null;
  const pc4 = m[1];
  return Number(pc4) >= 1000 ? pc4 : null;
}

/**
 * Lazy — the 4,070-row table (32 KB gzipped) is only fetched when a visitor
 * actually uses the location filter. Everyone else pays nothing.
 */
export async function pc4Centroid(pc4: string): Promise<Centroid | null> {
  const mod = await import("../data/pc4-centroids.json");
  const table = (mod.default as unknown as { pc4: Record<string, [number, number]> }).pc4;
  const hit = table[pc4];
  if (!hit) return null;
  const c = { lat: hit[0], lon: hit[1] };
  // Same rule as cityCentroid: an unusable coordinate is no coordinate. Here it
  // is the visitor's own origin, so every distance on the page would be NaN —
  // "postcode onbekend" is the honest answer, not a table full of "NaN km".
  return usable(c) ? c : null;
}
